# Pull the pre-built image from GitHub Container Registry
ARG  TAG_VERSION=latest
FROM ghcr.io/devlille/devlille/partners-connect-server:${TAG_VERSION}

ENTRYPOINT ["java","-jar","/app/application.jar"]