# .github/workflows/cd.yaml
# This workflow deploys an existing Docker image to Google Cloud Run.


name: CD - Deploy to Clever Cloud

on:
  push:
    tags:
      - '*.*.*'
  pull_request:

# Configure environment variables for easy reuse
env:
  REGION: 'europe-west1'
  REPOSITORY: 'partners-connect'
  IMAGE_NAME: 'partners-connect-server'
  CLEVER_TOKEN: ${{ secrets.CLEVERCLOUD_TOKEN }}
  CLEVER_SECRET: ${{ secrets.CLEVERCLOUD_SECRET }}

jobs:
  deploy-to-clevercloud:
    name: Deploy to Clever Cloud
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Pull image from Artifact Registry
        run: |
          docker pull ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:31840f41ca11f819136e2a7ce37481681e040504
          docker tag ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:31840f41ca11f819136e2a7ce37481681e040504 partners-connect-server:31840f41ca11f819136e2a7ce37481681e040504

      - name: Install clever-tools
        run: npm install -g clever-tools

      - name: Login to Clever Cloud
        run: |
          clever login
          clever profile

      - name: Deploy to Clever Cloud
        run: |
            clever login
          clever link ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever deploy --force

      - name: Get Clever Cloud app base URL
        id: clever_url
        run: |
          clever login
          APP_INFO=$(clever app info ${{ secrets.CLEVERCLOUD_APP_ID }} --json)
          echo "deploy_url=$(echo $APP_INFO | jq -r .deploy_url)" >> $GITHUB_OUTPUT

      - name: Update Clever Cloud environment variables
        run: |
          clever login
          clever env set SERVER_BASE_URL=${{ steps.clever_url.outputs.deploy_url }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set PROJECT_ID=${{ secrets.PROJECT_ID }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set FRONTEND_BASE_URL=${{ secrets.FRONTEND_BASE_URL }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set CRYPTO_KEY=${{ secrets.CRYPTO_KEY }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set CRYPTO_SALT=${{ secrets.CRYPTO_SALT }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set EXPOSED_DB_DRIVER=${{ secrets.EXPOSED_DB_DRIVER }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set EXPOSED_DB_URL=${{ secrets.EXPOSED_DB_URL }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set EXPOSED_DB_USER=${{ secrets.EXPOSED_DB_USER }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
          clever env set EXPOSED_DB_PASSWORD=${{ secrets.EXPOSED_DB_PASSWORD }} --app ${{ secrets.CLEVERCLOUD_APP_ID }}
