# .github/workflows/cd.yaml
# This workflow deploys an existing Docker image to Google Cloud Run.

name: CD - Deploy to Cloud Run

on:
  push:
    tags:
      - '*.*.*'

# Configure environment variables for easy reuse
env:
  PROJECT_ID: 'cms4partners-ce427'
  REGION: 'europe-west1'
  REPOSITORY: 'partners-connect'
  IMAGE_NAME: 'partners-connect-server'
  SERVICE_NAME: 'partners-connect-server'

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --platform managed
          
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format='value(status.url)')
          
          gcloud run services update ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --update-env-vars="SERVER_BASE_URL=$SERVICE_URL"
