# .github/workflows/ci.yaml
# This workflow builds and pushes a container image to Google Artifact Registry.
# It triggers on every push to the 'main' branch.

name: Build and Push Server Container

on:
  push:
    branches:
      - main

jobs:
  build-and-push-server:
    name: Build and Push Server to Artifact Registry
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: server

    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Generate OpenAPI documentation
        run: npm run bundle

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-server
          
          # Build the image
          docker build -t ${IMAGE_NAME}:${{ github.sha }} .
          
          # Tag as latest
          docker tag ${IMAGE_NAME}:${{ github.sha }} ${IMAGE_NAME}:latest
          
          # Push both tags
          docker push ${IMAGE_NAME}:${{ github.sha }}
          docker push ${IMAGE_NAME}:latest
